-- mods/lord_base/aliases.lua

-- These can also be helpful when using chat commands, for example /giveme
minetest.register_alias("stone", "lord_base:stone")
minetest.register_alias("stone_with_coal", "lord_base:stone_with_coal")
minetest.register_alias("stone_with_iron", "lord_base:stone_with_iron")
minetest.register_alias("dirt_with_grass", "lord_base:dirt_with_grass")
minetest.register_alias("dirt_with_grass_footsteps", "lord_base:dirt_with_grass_footsteps")
minetest.register_alias("dirt", "lord_base:dirt")
minetest.register_alias("sand", "lord_base:sand")
minetest.register_alias("gravel", "lord_base:gravel")
minetest.register_alias("sandstone", "lord_base:sandstone")
minetest.register_alias("clay", "lord_base:clay")
minetest.register_alias("brick", "lord_base:brick")
minetest.register_alias("tree", "lord_base:tree")
minetest.register_alias("jungletree", "lord_base:jungletree")
minetest.register_alias("junglegrass", "lord_base:junglegrass")
minetest.register_alias("leaves", "lord_base:leaves")
minetest.register_alias("cactus", "lord_base:cactus")
minetest.register_alias("papyrus", "lord_base:papyrus")
minetest.register_alias("bookshelf", "lord_base:bookshelf")
minetest.register_alias("glass", "lord_base:glass")
minetest.register_alias("wooden_fence", "lord_base:fence_wood")
minetest.register_alias("rail", "carts:rail")
minetest.register_alias("ladder", "lord_base:ladder_wood")
minetest.register_alias("wood", "lord_base:wood")
minetest.register_alias("mese", "lord_base:mese")
minetest.register_alias("cloud", "lord_base:cloud")
minetest.register_alias("water_flowing", "lord_base:water_flowing")
minetest.register_alias("water_source", "lord_base:water_source")
minetest.register_alias("lava_flowing", "lord_base:lava_flowing")
minetest.register_alias("lava_source", "lord_base:lava_source")
minetest.register_alias("torch", "lord_base:torch")
minetest.register_alias("sign_wall", "lord_base:sign_wall_wood")
minetest.register_alias("furnace", "lord_base:furnace")
minetest.register_alias("chest", "lord_base:chest")
minetest.register_alias("locked_chest", "lord_base:chest_locked")
minetest.register_alias("cobble", "lord_base:cobble")
minetest.register_alias("mossycobble", "lord_base:mossycobble")
minetest.register_alias("steelblock", "lord_base:steelblock")
minetest.register_alias("sapling", "lord_base:sapling")
minetest.register_alias("apple", "lord_base:apple")

minetest.register_alias("WPick", "lord_base:pick_wood")
minetest.register_alias("STPick", "lord_base:pick_stone")
minetest.register_alias("SteelPick", "lord_base:pick_steel")
minetest.register_alias("MesePick", "lord_base:pick_mese")
minetest.register_alias("WShovel", "lord_base:shovel_wood")
minetest.register_alias("STShovel", "lord_base:shovel_stone")
minetest.register_alias("SteelShovel", "lord_base:shovel_steel")
minetest.register_alias("WAxe", "lord_base:axe_wood")
minetest.register_alias("STAxe", "lord_base:axe_stone")
minetest.register_alias("SteelAxe", "lord_base:axe_steel")
minetest.register_alias("WSword", "lord_base:sword_wood")
minetest.register_alias("STSword", "lord_base:sword_stone")
minetest.register_alias("SteelSword", "lord_base:sword_steel")

minetest.register_alias("stick", "lord_base:stick")
minetest.register_alias("paper", "lord_base:paper")
minetest.register_alias("book", "lord_base:book")
minetest.register_alias("lump_of_coal", "lord_base:coal_lump")
minetest.register_alias("lump_of_iron", "lord_base:iron_lump")
minetest.register_alias("lump_of_clay", "lord_base:clay_lump")
minetest.register_alias("steel_ingot", "lord_base:steel_ingot")
minetest.register_alias("clay_brick", "lord_base:clay_brick")
minetest.register_alias("snow", "lord_base:snow")

-- 'mese_block' was used for a while for the block form of mese
minetest.register_alias("lord_base:mese_block", "lord_base:mese")

-- Aliases for corrected pine node names
minetest.register_alias("lord_base:pinetree", "lord_base:pine_tree")
minetest.register_alias("lord_base:pinewood", "lord_base:pine_wood")

minetest.register_alias("lord_base:ladder", "lord_base:ladder_wood")
minetest.register_alias("lord_base:sign_wall", "lord_base:sign_wall_wood")
